# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Test OOI Data Labs Book
author: The OOI Data Labs Community
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/seagrinch/book-test  # Online location of your book
  path_to_book: mybook  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true

# Adding launch buttons
launch_buttons:
  jupyterhub_url: https://jupyter.oceanobservatories.org
  colab_url: "https://colab.research.google.com"

# Add this for Plotly
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    suppress_warnings: ["mystnb.unknown_mime_type"]
 